# Deployment configuration

repo-name    = "SOAR-all-alarms-to-sec-hub"
part-of      = 'soar'


[SAM]
stack-name   = "INFRA-all-alarms-to-sec-hub"
profile      = "security-account"
regions      = '{main-region}'


[[post-SAM-CloudFormation]]
name         = "INFRA-local-alarm-events-to-sec-hub-bus"
template     = 'cloudformation/local-alarm-events-to-sec-hub-bus.yaml'
account      = '{all-accounts}'
regions      = '{all-regions}'


