AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This SAM project creates Security Hub findings for all CloudWatch Alarm Change events
  to the state ALARM. Deploy it once, in the Security account in North Virginia.

Globals:
  Function:
    Timeout: 30

Parameters:
  AlarmTypeForASFF:
    Type: String
    Description: The alarm type for the ASFF finding created
    Default: buzzcloud-infrastructural-alarms
  CompanyName:
    Type: String
    Description: The CompanyName for the ASFF finding created
    Default: Buzzcloud Infrastructural Alarms

Resources:
  AllAlarmsToSecHubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_function
      Handler: lambda/app.lambda_handler
      Runtime: python3.9
      Events:
        AlarmRaised:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.cloudwatch
              detail-type:
                - CloudWatch Alarm State Change
              detail:
                state:
                  value:
                    - ALARM
      Environment:
        Variables:
          ALARM_TYPE: !Ref AlarmTypeForASFF
          COMPANY_NAME: !Ref CompanyName
      Policies:
        - Statement:
            - Sid: AssumeTheRole
              Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: 'arn:aws:iam::*:role/SecurityHubRole'
            - Sid: SecHubPermissions
              Effect: Allow
              Action:
                - securityhub:BatchImportFindings
              Resource: '*'
